version: "3.8"
services:
  rabbitmq:
    image: rabbitmq-with-delay
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER} # on file .env
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS} # on file .env

volumes:
  rabbitmq_data:
